name: Main build

on: push

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Check out repo
        uses: actions/checkout@v2

      - name: Set up JDK 6
        uses: actions/setup-java@v1
        with:
          java-version: 6

      - name: Cache Maven
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository/
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven-

      - name: Compile
        run: mvn compile --batch-mode

      - name: Run tests
        run: mvn test --batch-mode

      - name: Run integration test
        run: mvn invoker:run --batch-mode --activate-profiles run-its
