name: Main build

on: push

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Check out repo
        uses: actions/checkout@v2

      - name: Set up JDK 7
        uses: actions/setup-java@v1
        with:
          java-version: 7

      - name: Cache Maven
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository/
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven-

      - name: Compile
        run: mvn compile --batch-mode

      - name: Run tests
        run: mvn test --batch-mode

      - name: Run integration test
        run: mvn verify --batch-mode -DskipTests -Prun-its

      - name: Print failed integration test logs
        if: ${{ failure() }}
        run: cat target/it/*/build.log
