name: verify
on: push
jobs:
  verify:
    strategy:
      matrix:
        platform: [windows-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Check out repo
        uses: actions/checkout@v2

      - name: Set up JDK 7
        uses: actions/setup-java@v1
        with:
          java-version: 7

      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Maven verify
        run: mvn -B verify -Prun-its

      - name: Print integration test logs
        run: cat target/it/*/build.log

      - name: Print failed integration test logs
        if: failure()
        run: cat target/it/*/build.log
        
      - uses: actions/upload-artifact@v2
        if: failure()
        with:
          path: target
