name: verify
on: [push, pull_request, workflow_dispatch]
jobs:
  verify:
    strategy:
      matrix:
        platform: [ubuntu-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up JDK 7
        uses: actions/setup-java@v1
        with:
          java-version: 7

      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Maven verify
        run: mvn -B verify -Prun-its

      - uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: it-build-logs
          path: target/it/*/*.log

      - name: Foresight Coverage Report Uploader
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: coverage-artifact
          path: target/site/jacoco/jaoco.xml
